language: node.js
sudo: required
services:
  - docker

before_install:
  - docker build -t adarsh2day/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adarsh2day/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app:  "docker-react"
  env:  "DockerReact-env"
  bucket_name:  "elasticbeanstalk-eu-central-1-759161019306"
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

